name: Test and lint PR
on:
  workflow_call:
jobs:
  lint:
    runs-on: alpine-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Start lint
        run: npm run lint
  unit-tests:
    runs-on: alpine-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Start unit-tests
        run: npm run test:coverage
